"use client";

import jsPDF from "jspdf";

type Appliance = {
  name: string;
  monthlyKwh: number;
  monthlyCost: number;
};

const forecastMonths = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export default function PdfReportButton({
  appliances,
  propertyName,
  propertyType,
  currency,
  totalFloors,
  totalRooms,
  totalDevices,
}: {
  appliances: Appliance[];
  propertyName: string;
  propertyType: string;
  currency: string;
  totalFloors: number;
  totalRooms: number;
  totalDevices: number;
}) {
  const generatePdf = () => {
    const doc = new jsPDF();

    const totalKwh = appliances.reduce(
      (sum, item) => sum + item.monthlyKwh,
      0
    );

    const totalCost = appliances.reduce(
      (sum, item) => sum + item.monthlyCost,
      0
    );

    const annualCost = totalCost * 12;
    const monthlySaving = totalCost * 0.15;
    const annualSaving = monthlySaving * 12;

    const highest =
      appliances.length > 0
        ? appliances.reduce((max, item) =>
            item.monthlyKwh > max.monthlyKwh ? item : max
          )
        : null;

    const topConsumers = [...appliances]
      .sort((a, b) => b.monthlyKwh - a.monthlyKwh)
      .slice(0, 5);

    const pageWidth = doc.internal.pageSize.getWidth();

    function addHeader(title: string) {
      doc.setFillColor(22, 163, 74);
      doc.rect(0, 0, pageWidth, 18, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.text("WattSave AI", 14, 12);

      doc.setFontSize(10);
      doc.text(title, pageWidth - 70, 12);

      doc.setTextColor(0, 0, 0);
    }

    function addFooter() {
      const pageHeight = doc.internal.pageSize.getHeight();

      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      doc.text(
        "Generated by WattSave AI - Energy Intelligence Report",
        14,
        pageHeight - 10
      );
      doc.setTextColor(0, 0, 0);
    }

    function checkPage(y: number) {
      if (y > 265) {
        addFooter();
        doc.addPage();
        addHeader("Energy Report");
        return 30;
      }

      return y;
    }

    let y = 30;

    addHeader("Energy Report");

    doc.setFontSize(24);
    doc.setTextColor(22, 163, 74);
    doc.text("WattSave AI Energy Report", 14, y);

    y += 10;
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(11);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, y);

    y += 14;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("Property Information", 14, y);

    y += 10;
    doc.setFontSize(12);
    doc.text(`Property Name: ${propertyName}`, 14, y);
    y += 8;
    doc.text(`Property Type: ${propertyType}`, 14, y);
    y += 8;
    doc.text(`Total Floors: ${totalFloors}`, 14, y);
    y += 8;
    doc.text(`Total Rooms: ${totalRooms}`, 14, y);
    y += 8;
    doc.text(`Total Devices: ${totalDevices}`, 14, y);
    y += 8;
    doc.text(`Currency: ${currency}`, 14, y);

    y += 15;

    doc.setFillColor(240, 253, 244);
    doc.roundedRect(14, y, 182, 42, 4, 4, "F");

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("Energy Summary", 20, y + 10);

    doc.setFontSize(12);
    doc.text(`Monthly Energy: ${totalKwh.toFixed(2)} kWh`, 20, y + 22);
    doc.text(`Monthly Cost: ${totalCost.toFixed(3)} ${currency}`, 20, y + 31);
    doc.text(`Annual Cost: ${annualCost.toFixed(3)} ${currency}`, 105, y + 31);

    y += 56;

    doc.setFontSize(16);
    doc.text("12-Month Energy Forecast", 14, y);

    y += 10;
    doc.setFontSize(12);
    doc.text(`Forecast Monthly Cost: ${totalCost.toFixed(3)} ${currency}`, 14, y);
    y += 8;
    doc.text(`Projected Annual Cost: ${annualCost.toFixed(3)} ${currency}`, 14, y);
    y += 8;
    doc.text("Assumption: same monthly usage for the next 12 months.", 14, y);

    y += 12;
    doc.setFontSize(10);

    forecastMonths.forEach((month, index) => {
      y = checkPage(y);

      const x = index < 6 ? 18 : 105;
      const rowY = index < 6 ? y + index * 7 : y + (index - 6) * 7;

      doc.text(`${month}: ${totalCost.toFixed(3)} ${currency}`, x, rowY);

      if (index === 11) {
        y = rowY + 12;
      }
    });

    y = checkPage(y);

    doc.setFontSize(16);
    doc.text("Savings Opportunity", 14, y);

    y += 10;
    doc.setFontSize(12);
    doc.text(
      `Potential Monthly Saving: ${monthlySaving.toFixed(3)} ${currency}`,
      14,
      y
    );

    y += 8;
    doc.text(
      `Potential Annual Saving: ${annualSaving.toFixed(3)} ${currency}`,
      14,
      y
    );

    y += 16;

    if (highest) {
      doc.setFillColor(254, 242, 242);
      doc.roundedRect(14, y, 182, 34, 4, 4, "F");

      doc.setFontSize(16);
      doc.text("Highest Energy Consumer", 20, y + 10);

      doc.setFontSize(12);
      doc.text(`Device: ${highest.name}`, 20, y + 20);
      doc.text(
        `Consumption: ${highest.monthlyKwh.toFixed(2)} kWh/month`,
        20,
        y + 29
      );

      y += 48;
    }

    doc.setFontSize(16);
    doc.text("Top Energy Consumers", 14, y);

    y += 10;

    if (topConsumers.length === 0) {
      doc.setFontSize(11);
      doc.text("No devices added yet.", 14, y);
      y += 10;
    } else {
      topConsumers.forEach((item, index) => {
        y = checkPage(y);

        doc.setFontSize(11);
        doc.text(
          `${index + 1}. ${item.name} - ${item.monthlyKwh.toFixed(
            2
          )} kWh/month`,
          18,
          y
        );

        y += 8;
      });
    }

    y += 10;
    y = checkPage(y);

    doc.setFontSize(16);
    doc.text("Device Breakdown", 14, y);

    y += 10;

    doc.setFillColor(245, 245, 245);
    doc.rect(14, y - 6, 182, 9, "F");

    doc.setFontSize(10);
    doc.text("Device", 18, y);
    doc.text("kWh/month", 105, y);
    doc.text(`Cost/month (${currency})`, 150, y);

    y += 8;
    doc.line(14, y - 4, 196, y - 4);

    appliances.forEach((item) => {
      y = checkPage(y);

      const deviceName =
        item.name.length > 38 ? item.name.substring(0, 38) + "..." : item.name;

      doc.setFontSize(10);
      doc.text(deviceName, 18, y);
      doc.text(item.monthlyKwh.toFixed(2), 110, y);
      doc.text(item.monthlyCost.toFixed(3), 158, y);

      y += 8;
    });

    y += 12;
    y = checkPage(y);

    doc.setFontSize(16);
    doc.text("AI Recommendations", 14, y);

    y += 10;
    doc.setFontSize(11);

    const recommendations = highest
      ? [
          `${highest.name} is the highest energy consumer in this report.`,
          "Review daily operating hours and reduce unnecessary runtime.",
          "Consider replacing old high-wattage appliances with efficient alternatives.",
          "Focus first on AC, lighting, pumps, and kitchen appliances for savings.",
          "A 15% reduction in high-consumption devices can create measurable annual savings.",
        ]
      : [
          "Add devices to rooms to generate useful energy recommendations.",
          "Use appliance presets for more accurate energy estimates.",
        ];

    recommendations.forEach((item) => {
      y = checkPage(y);

      const lines = doc.splitTextToSize(`• ${item}`, 170);
      doc.text(lines, 18, y);
      y += lines.length * 6 + 3;
    });

    addFooter();

    const safePropertyName = propertyName.replace(/[^a-zA-Z0-9]/g, "_");

    doc.save(`WattSave_${safePropertyName}_Energy_Report.pdf`);
  };

  return (
    <button
      onClick={generatePdf}
      className="bg-blue-600 text-white px-5 py-3 rounded-lg hover:bg-blue-700"
    >
      Export PDF Report
    </button>
  );
}